{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 22158,
          "sha512": "d8e66a0ab442e0fc30fe5ef237584a9b7fa3d8464f694f58d231548e49205a0079d4760b55fc86f1d99d7cb078a20665130c71f51fdaa56f3a825130c1dd5310",
          "sha256": "7ad3c9978ec2b18f7fa7f7a1edefdca73593753f1b62989a0964d6b74ca96af2",
          "sha1": "f1107e274aad9344f230935cccc957dd59fe86a5",
          "md5": "58e6f480fdf97cfb89d1c46bd3d36da8"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_profile-1.0.aar",
          "url": "share_plus_profile-1.0.aar",
          "size": 22158,
          "sha512": "d8e66a0ab442e0fc30fe5ef237584a9b7fa3d8464f694f58d231548e49205a0079d4760b55fc86f1d99d7cb078a20665130c71f51fdaa56f3a825130c1dd5310",
          "sha256": "7ad3c9978ec2b18f7fa7f7a1edefdca73593753f1b62989a0964d6b74ca96af2",
          "sha1": "f1107e274aad9344f230935cccc957dd59fe86a5",
          "md5": "58e6f480fdf97cfb89d1c46bd3d36da8"
        }
      ]
    }
  ]
}
