{
  "formatVersion": "1.1",
  "component": {
    "group": "com.amwal.amwal_pay",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 20860562,
          "sha512": "a85e89c92399fc01725cca27083cc51e3caa4cdda4afb2e2a40e93b7d111680f55364db85d1a3ecca663299000d1393c73aa482a63712e6b97c309c914c99f1e",
          "sha256": "b45c7775107d62cad407d2f39ed8bfccbdf82bd3c835c4af5ba9e71ca63c5ac0",
          "sha1": "6e5fe3cbc11e13274ca9ce9a3b313d824fb340f9",
          "md5": "9981747f5574aad9a46670c76c4ad926"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.pathprovider",
          "module": "path_provider_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "fman.ge.smart_auth",
          "module": "smart_auth_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 20860562,
          "sha512": "a85e89c92399fc01725cca27083cc51e3caa4cdda4afb2e2a40e93b7d111680f55364db85d1a3ecca663299000d1393c73aa482a63712e6b97c309c914c99f1e",
          "sha256": "b45c7775107d62cad407d2f39ed8bfccbdf82bd3c835c4af5ba9e71ca63c5ac0",
          "sha1": "6e5fe3cbc11e13274ca9ce9a3b313d824fb340f9",
          "md5": "9981747f5574aad9a46670c76c4ad926"
        }
      ]
    }
  ]
}
