{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13153,
          "sha512": "fa766c0a41b77ff7d6b40385fb3ba8d4e0997ed5e6e8d9b6b4d47b437206e24c199467842edda973e2f8c3ccd92257015d53fea50c07bc77bdbebfe04acff0b1",
          "sha256": "69e4664b9beb49d1f3d5846f44bcebde58415ea499adbd1e9af34ef446fdd39e",
          "sha1": "9561c24cd5d8a166a93bef16a311c8f20533274c",
          "md5": "c2192188e171c7f7d4ee9d97d0f8bd1a"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13153,
          "sha512": "fa766c0a41b77ff7d6b40385fb3ba8d4e0997ed5e6e8d9b6b4d47b437206e24c199467842edda973e2f8c3ccd92257015d53fea50c07bc77bdbebfe04acff0b1",
          "sha256": "69e4664b9beb49d1f3d5846f44bcebde58415ea499adbd1e9af34ef446fdd39e",
          "sha1": "9561c24cd5d8a166a93bef16a311c8f20533274c",
          "md5": "c2192188e171c7f7d4ee9d97d0f8bd1a"
        }
      ]
    }
  ]
}
