{
  "formatVersion": "1.1",
  "component": {
    "group": "fman.ge.smart_auth",
    "module": "smart_auth_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "smart_auth_release-1.0.aar",
          "url": "smart_auth_release-1.0.aar",
          "size": 37376,
          "sha512": "0795feec82c1684f0f11f08aa06b959a981be28edbd716dcaff4b7022894f5e3ba82dcdfda13252b2264bcb9edc1618f7572111450d5dbc5a37f2ba02eb65e1f",
          "sha256": "fc44f4db6910de00855b56a10129746c24de1392d6894f622ebe28d464d33169",
          "sha1": "87ee9e67602a7b41536449876590b1a434490230",
          "md5": "71af33557dec63af9dfcdbb5173c6606"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-b4fb11214dd2dda6ce012dd98ea498e9e8b91262"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.4.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "smart_auth_release-1.0.aar",
          "url": "smart_auth_release-1.0.aar",
          "size": 37376,
          "sha512": "0795feec82c1684f0f11f08aa06b959a981be28edbd716dcaff4b7022894f5e3ba82dcdfda13252b2264bcb9edc1618f7572111450d5dbc5a37f2ba02eb65e1f",
          "sha256": "fc44f4db6910de00855b56a10129746c24de1392d6894f622ebe28d464d33169",
          "sha1": "87ee9e67602a7b41536449876590b1a434490230",
          "md5": "71af33557dec63af9dfcdbb5173c6606"
        }
      ]
    }
  ]
}
